### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by blaqshyd** [metatony/simple-commerce#6]
I think it's best to create a navbar so we can just use routes, as we might be working on different screens at the same time. I just pulled and the default is Details screen

**Comment by metatony** [comment]
okay, that's better. my bad

**Comment by blaqshyd** [comment]
You're familiar with how the issue works right? If there's an issue you want to solve or be attended to. You just create it here

**Comment by blaqshyd** [comment]
Fixed the routing and navigation
